import { BBH_Sans_Bogle } from "next/font/google";
import "./globals.css";

const bbhSans = BBH_Sans_Bogle({
  weight: "400"
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${bbhSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
